font_family JetBrainsMono Nerd Font Mono
font_size 12.0
copy_on_select clipboard
strip_trailing_spaces smart
foreground #ced8f3
background #120c1f
cursor #ced8f3
color0 #120c1f
color1 #5648a9
color2 #2965e9
color3 #5463e7
color4 #b546e3
color5 #5d98fc
color6 #40c1f9
color7 #ced8f3
color8 #9097aa
color9 #5648a9
color10 #2965e9
color11 #5463e7
color12 #b546e3
color13 #5d98fc
color14 #40c1f9
color15 #ced8f3
