# Empty monitor = fallback wallpaper for every monitor, whichever connector it is on.
wallpaper {
    monitor =
    path = /home/yuvalm/Pictures/purple-noir-neon.jpg
}


disable_splash_rendering = true,
splash = false
